# Generated by Django 3.2.9 on 2021-11-18 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='questions',
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('TEXT', 'Text Field'), ('EMAIL', 'Email Field'), ('MULTIPLE', 'Multiple Choices'), ('DROPDOWN', 'Dropdown')], default='TEXT', max_length=10)),
                ('question', models.CharField(max_length=10000)),
                ('choices', models.JSONField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='form_builder.form')),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_to', to='form_builder.question'),
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
